const hobbies = [
  { id: 1, hobby: "photography" },
  { id: 2, hobby: "cooking" },
  { id: 3, hobby: "gardening" },
  { id: 4, hobby: "reading" },
  { id: 5, hobby: "hiking" },
  { id: 6, hobby: "painting" },
  { id: 7, hobby: "music" },
  { id: 8, hobby: "dancing" },
  { id: 9, hobby: "yoga" },
  { id: 10, hobby: "fishing" },
  { id: 11, hobby: "cycling" },
  { id: 12, hobby: "gaming" },
  { id: 13, hobby: "knitting" },
  { id: 14, hobby: "woodworking" },
  { id: 15, hobby: "chess" },
  { id: 16, hobby: "swimming" },
  { id: 17, hobby: "birdwatching" },
  { id: 18, hobby: "camping" },
  { id: 19, hobby: "writing" },
  { id: 20, hobby: "pottery" },
  { id: 21, hobby: "meditation" },
  { id: 22, hobby: "astronomy" },
  { id: 23, hobby: "filmmaking" },
  { id: 24, hobby: "calligraphy" },
  { id: 25, hobby: "collecting" },
  { id: 26, hobby: "surfing" },
  { id: 27, hobby: "running" },
  { id: 28, hobby: "sewing" },
  { id: 29, hobby: "drawing" },
  { id: 30, hobby: "climbing" },
  { id: 31, hobby: "tennis" },
  { id: 32, hobby: "basketball" },
  { id: 33, hobby: "volleyball" },
  { id: 34, hobby: "football" },
  { id: 35, hobby: "skiing" },
  { id: 36, hobby: "archery" },
  { id: 37, hobby: "sailing" },
  { id: 38, hobby: "baking" },
  { id: 39, hobby: "blogging" },
  { id: 40, hobby: "skateboarding" },
];

export default hobbies;
